openapi: 3.0.0
x-stoplight:
  id: 18vtx0d9afi3b
info:
  title: Consent-Manager
  version: '1.0'
  description: Consent Manager
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
  /user: {}
components:
  schemas:
    Consent-Form:
      title: Consent-Form
      x-stoplight:
        id: ti854s4kspqie
      type: object
      properties:
        id:
          type: string
          description: UUID ID of form
          format: uuid
        name:
          type: string
          description: Simple name of form
        description:
          type: string
          description: Description of form
        itemId:
          type: string
          description: Cat ID of resource
        itemType:
          type: string
          description: Type of resource
          enum:
            - resource_group
            - resource
        purposes:
          type: array
          description: List of purposes
          items:
            $ref: '#/components/schemas/Purpose'
        expiryDuration:
          type: string
          description: How long a consent artefact generated from thisform will last
          pattern: '^(-?)P(?=\d|T\d)(?:(\d+)Y)?(?:(\d+)M)?(?:(\d+)([DW]))?(?:T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+(?:\.\d+)?)S)?)?$'
          format: duration
        consentFormStats:
          $ref: '#/components/schemas/Consent-Form-Stats'
      required:
        - id
        - name
        - description
        - itemId
        - itemType
        - purposes
        - expiryDuration
    Consent-Form-Stats:
      title: Consent-Form-Stats
      x-stoplight:
        id: 32u08fgjwdk85
      type: object
      properties:
        dataPrincipalCount:
          type: integer
        artifactCount:
          type: integer
      description: 'Stats for a consent form '
    Purpose:
      title: Purpose
      x-stoplight:
        id: jyhjlpu5iug53
      type: object
      properties:
        id:
          type: string
          description: UUID ID of purpose
          format: uuid
        name:
          type: string
        description:
          type: string
      required:
        - id
        - name
    Data-Principal:
      title: Data-Principal
      x-stoplight:
        id: ydql93jmjxe2a
      type: object
      properties:
        id:
          type: string
          description: UUID ID of data principal
          format: uuid
        ppbNo:
          type: string
          description: PPB number
        nameRegional:
          type: string
          description: Name in regional script
        nameEnglish:
          type: string
          description: Name in English
        dataPrincipalStats:
          $ref: '#/components/schemas/Data-Principal-Stats'
      required:
        - id
        - ppbNo
        - nameEnglish
    Data-Principal-Stats:
      title: Data-Principal-Stats
      x-stoplight:
        id: rff0j8ljamfv8
      type: object
      properties:
        artifactCount:
          type: integer
        accessLogCount:
          type: integer
    AIU:
      title: AIU
      x-stoplight:
        id: jygt2ro3zd9ce
      type: object
      properties:
        id:
          type: string
          description: IUDX user ID of AIU
          format: uuid
        name:
          type: object
          required:
            - firstName
            - lastName
          properties:
            firstName:
              type: string
            lastName:
              type: string
        email:
          type: string
        aiuStats:
          $ref: '#/components/schemas/AIU-Stats'
      required:
        - id
        - name
        - email
    AIU-Stats:
      title: AIU-Stats
      x-stoplight:
        id: ojnrtjbu9ojop
      type: object
      properties:
        activeArtifactCount:
          type: integer
        accessLogCount:
          type: integer
    AIP:
      title: AIP
      x-stoplight:
        id: h80aoxodvm5r8
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: object
          required:
            - firstName
            - lastName
          properties:
            firstName:
              type: string
            lastName:
              type: string
        email:
          type: string
      required:
        - id
        - name
        - email
    Consent-Artifact:
      title: Consent-Artifact
      x-stoplight:
        id: q0amvhva2o2fb
      type: object
      properties:
        id:
          type: string
          description: UUID ID of artifact
          format: uuid
        aiu:
          $ref: '#/components/schemas/AIU'
        aip:
          $ref: '#/components/schemas/AIP'
        dataPrincipal:
          $ref: '#/components/schemas/Data-Principal'
        purposes:
          type: array
          items:
            $ref: '#/components/schemas/Purpose'
        itemId:
          type: string
        itemType:
          type: string
          enum:
            - resource_group
            - resource
        status:
          type: string
          enum:
            - active
            - revoked
        expiry:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        consentArtifactStats:
          $ref: '#/components/schemas/Consent-Artifact-Stats'
      required:
        - id
        - aiu
        - aip
        - dataPrincipal
        - purposes
        - itemId
        - itemType
        - status
        - expiry
        - createdAt
        - updatedAt
    Consent-Artifact-Stats:
      title: Consent-Artifact-Stats
      x-stoplight:
        id: vimv51qjgikhf
      type: object
      properties:
        accessLogCount:
          type: integer
      required:
        - accessLogCount
    Access-Log:
      title: Access-Log
      x-stoplight:
        id: 863xx35dw6y26
      type: object
      properties:
        id:
          type: string
          format: uuid
        artifact:
          $ref: '#/components/schemas/Consent-Artifact'
        createdAt:
          type: string
          format: date-time
      required:
        - id
  securitySchemes:
    IUDX AAA Identity Token:
      type: http
      scheme: bearer
