openapi: 3.0.0
x-stoplight:
  id: 18vtx0d9afi3b
info:
  title: Consent-Manager
  version: '1.0'
  description: Consent Manager
servers:
  - url: 'http://localhost:3000'
paths:
  /consent/purposes:
    parameters: []
    get:
      summary: 'Get all purposes - AIU, AIP'
      operationId: get-consent-purposes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Purpose'
                required:
                  - type
                  - title
                  - results
              examples:
                Example 1:
                  value:
                    type: string
                    title: string
                    results:
                      - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                        name: string
                        description: string
      description: Get all purposes
      security:
        - IUDX AAA Identity Token: []
      tags:
        - Purposes APIs
  /consent/forms:
    parameters: []
    get:
      summary: View consent forms - AIP
      operationId: get-consent-forms
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Consent-Form'
              examples:
                Example 1:
                  value:
                    type: string
                    title: string
                    results:
                      - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                        name: string
                        description: string
                        itemId: string
                        itemType: resource_group
                        purposes:
                          - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                            name: string
                            description: string
                        expiryDuration: P1Y
                        consentFormStats:
                          dataPrincipalCount: 0
                          artifactCount: 0
      description: AIP views all consent forms they have created
      tags:
        - Consent Form APIs
      security:
        - IUDX AAA Identity Token: []
      parameters:
        - schema:
            type: array
          in: query
          name: purposes
          description: Search by list of purposes
        - schema:
            type: string
          in: query
          name: item
          description: Search by an item ID (Cat ID)
    post:
      summary: Create consent form - AIP
      operationId: post-consent-forms
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  results:
                    $ref: '#/components/schemas/Consent-Form'
              examples:
                Example 1:
                  value:
                    type: string
                    title: string
                    results:
                      id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                      name: string
                      description: string
                      itemId: string
                      itemType: resource_group
                      purposes:
                        - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                          name: string
                          description: string
                      expiryDuration: P1Y
                      consentFormStats:
                        dataPrincipalCount: 0
                        artifactCount: 0
      description: Create a consent form
      security:
        - IUDX AAA Identity Token: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                purposes:
                  type: array
                  items:
                    type: string
                    format: uuid
                dataPrincipals:
                  type: array
                  description: PPB numbers
                  items:
                    type: string
                itemId:
                  type: string
                  description: cat ID of resource
                itemType:
                  type: string
                  enum:
                    - resource_group
                    - resource
                expiryDuration:
                  type: string
                  format: duration
              required:
                - name
                - description
                - purposes
                - dataPrincipals
                - itemId
                - itemType
                - expiryDuration
            examples:
              Example 1:
                value:
                  name: string
                  description: string
                  purposes:
                    - 497f6eca-6276-4993-bfeb-53cbbbba6f08
                  dataPrincipals:
                    - string
                  itemId: string
                  itemType: resource_group
                  expiryDuration: P1Y
      tags:
        - Consent Form APIs
    put:
      summary: Update an existing consent form - AIP
      operationId: put-consent-forms
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Consent-Form'
              examples:
                Example 1:
                  value:
                    type: string
                    title: string
                    results:
                      - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                        name: string
                        description: string
                        itemId: string
                        itemType: resource_group
                        purposes:
                          - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                            name: string
                            description: string
                        expiryDuration: P1Y
                        consentFormStats:
                          dataPrincipalCount: 0
                          artifactCount: 0
      description: Update purposes/data principals
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                request:
                  type: array
                  minItems: 1
                  uniqueItems: true
                  maxItems: 100
                  items:
                    type: object
                    additionalProperties: false
                    properties:
                      formId:
                        type: string
                        format: uuid
                      purposes:
                        type: array
                        items:
                          type: string
                          format: uuid
                      dataPrincipals:
                        type: array
                        items:
                          type: string
                    required:
                      - formId
                      - purposes
                      - dataPrincipals
              required:
                - request
            examples:
              Example 1:
                value:
                  request:
                    - formId: 126460ed-49b2-4c69-849a-bd8904ec5d8f
                      purposes:
                        - 497f6eca-6276-4993-bfeb-53cbbbba6f08
                      dataPrincipals:
                        - string
      tags:
        - Consent Form APIs
    delete:
      summary: Delete consent forms - AIP
      operationId: delete-consent-forms
      responses:
        '200':
          description: OK
      description: Delete list of consent forms
      security:
        - IUDX AAA Identity Token: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                formIds:
                  type: array
                  uniqueItems: true
                  minItems: 1
                  maxItems: 100
                  items:
                    type: string
                    format: uuid
            examples:
              Example 1:
                value:
                  formIds:
                    - 497f6eca-6276-4993-bfeb-53cbbbba6f08
      tags:
        - Consent Form APIs
components:
  schemas:
    Consent-Form:
      title: Consent-Form
      x-stoplight:
        id: ti854s4kspqie
      type: object
      properties:
        id:
          type: string
          description: UUID ID of form
          format: uuid
        name:
          type: string
          description: Simple name of form
        description:
          type: string
          description: Description of form
        itemId:
          type: string
          description: Cat ID of resource
        itemType:
          type: string
          description: Type of resource
          enum:
            - resource_group
            - resource
        purposes:
          type: array
          description: List of purposes
          items:
            $ref: '#/components/schemas/Purpose'
        expiryDuration:
          type: string
          description: How long a consent artefact generated from thisform will last
          pattern: '^(-?)P(?=\d|T\d)(?:(\d+)Y)?(?:(\d+)M)?(?:(\d+)([DW]))?(?:T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+(?:\.\d+)?)S)?)?$'
          format: duration
        consentFormStats:
          $ref: '#/components/schemas/Consent-Form-Stats'
      required:
        - id
        - name
        - description
        - itemId
        - itemType
        - purposes
        - expiryDuration
    Consent-Form-Stats:
      title: Consent-Form-Stats
      x-stoplight:
        id: 32u08fgjwdk85
      type: object
      properties:
        dataPrincipalCount:
          type: integer
        artifactCount:
          type: integer
      description: 'Stats for a consent form '
    Purpose:
      title: Purpose
      x-stoplight:
        id: jyhjlpu5iug53
      type: object
      properties:
        id:
          type: string
          description: UUID ID of purpose
          format: uuid
        name:
          type: string
        description:
          type: string
      required:
        - id
        - name
    Data-Principal:
      title: Data-Principal
      x-stoplight:
        id: ydql93jmjxe2a
      type: object
      properties:
        id:
          type: string
          description: UUID ID of data principal
          format: uuid
        ppbNo:
          type: string
          description: PPB number
        nameRegional:
          type: string
          description: Name in regional script
        nameEnglish:
          type: string
          description: Name in English
        dataPrincipalStats:
          $ref: '#/components/schemas/Data-Principal-Stats'
      required:
        - id
        - ppbNo
        - nameEnglish
    Data-Principal-Stats:
      title: Data-Principal-Stats
      x-stoplight:
        id: rff0j8ljamfv8
      type: object
      properties:
        artifactCount:
          type: integer
        accessLogCount:
          type: integer
    AIU:
      title: AIU
      x-stoplight:
        id: jygt2ro3zd9ce
      type: object
      properties:
        id:
          type: string
          description: IUDX user ID of AIU
          format: uuid
        name:
          type: object
          required:
            - firstName
            - lastName
          properties:
            firstName:
              type: string
            lastName:
              type: string
        email:
          type: string
        aiuStats:
          $ref: '#/components/schemas/AIU-Stats'
      required:
        - id
        - name
        - email
    AIU-Stats:
      title: AIU-Stats
      x-stoplight:
        id: ojnrtjbu9ojop
      type: object
      properties:
        activeArtifactCount:
          type: integer
        accessLogCount:
          type: integer
    AIP:
      title: AIP
      x-stoplight:
        id: h80aoxodvm5r8
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: object
          required:
            - firstName
            - lastName
          properties:
            firstName:
              type: string
            lastName:
              type: string
        email:
          type: string
      required:
        - id
        - name
        - email
    Consent-Artifact:
      title: Consent-Artifact
      x-stoplight:
        id: q0amvhva2o2fb
      type: object
      properties:
        id:
          type: string
          description: UUID ID of artifact
          format: uuid
        aiu:
          $ref: '#/components/schemas/AIU'
        aip:
          $ref: '#/components/schemas/AIP'
        dataPrincipal:
          $ref: '#/components/schemas/Data-Principal'
        purposes:
          type: array
          items:
            $ref: '#/components/schemas/Purpose'
        itemId:
          type: string
        itemType:
          type: string
          enum:
            - resource_group
            - resource
        status:
          type: string
          enum:
            - active
            - revoked
        expiry:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        consentArtifactStats:
          $ref: '#/components/schemas/Consent-Artifact-Stats'
      required:
        - id
        - aiu
        - aip
        - dataPrincipal
        - purposes
        - itemId
        - itemType
        - status
        - expiry
        - createdAt
        - updatedAt
    Consent-Artifact-Stats:
      title: Consent-Artifact-Stats
      x-stoplight:
        id: vimv51qjgikhf
      type: object
      properties:
        accessLogCount:
          type: integer
      required:
        - accessLogCount
    Access-Log:
      title: Access-Log
      x-stoplight:
        id: 863xx35dw6y26
      type: object
      properties:
        id:
          type: string
          format: uuid
        artifact:
          $ref: '#/components/schemas/Consent-Artifact'
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - artifact
        - createdAt
  securitySchemes:
    IUDX AAA Identity Token:
      type: http
      scheme: bearer
